//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBookingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingServices
    {
        public int BookingServiceId { get; set; }
        public Nullable<int> BookingId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> ServiceDate { get; set; }
    
        public virtual Bookings Bookings { get; set; }
        public virtual Services Services { get; set; }
    }
}
