//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBookingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomTypeServices
    {
        public int RoomTypeServiceId { get; set; }
        public Nullable<int> RoomTypeId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<bool> IncludedInPrice { get; set; }
    
        public virtual RoomTypes RoomTypes { get; set; }
        public virtual Services Services { get; set; }
    }
}
